 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/orbits", type: :request do
  # Orbit. As you add validations to Orbit, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Orbit.create! valid_attributes
      get orbits_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      orbit = Orbit.create! valid_attributes
      get orbit_url(orbit)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_orbit_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      orbit = Orbit.create! valid_attributes
      get edit_orbit_url(orbit)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Orbit" do
        expect {
          post orbits_url, params: { orbit: valid_attributes }
        }.to change(Orbit, :count).by(1)
      end

      it "redirects to the created orbit" do
        post orbits_url, params: { orbit: valid_attributes }
        expect(response).to redirect_to(orbit_url(Orbit.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Orbit" do
        expect {
          post orbits_url, params: { orbit: invalid_attributes }
        }.to change(Orbit, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post orbits_url, params: { orbit: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested orbit" do
        orbit = Orbit.create! valid_attributes
        patch orbit_url(orbit), params: { orbit: new_attributes }
        orbit.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the orbit" do
        orbit = Orbit.create! valid_attributes
        patch orbit_url(orbit), params: { orbit: new_attributes }
        orbit.reload
        expect(response).to redirect_to(orbit_url(orbit))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        orbit = Orbit.create! valid_attributes
        patch orbit_url(orbit), params: { orbit: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested orbit" do
      orbit = Orbit.create! valid_attributes
      expect {
        delete orbit_url(orbit)
      }.to change(Orbit, :count).by(-1)
    end

    it "redirects to the orbits list" do
      orbit = Orbit.create! valid_attributes
      delete orbit_url(orbit)
      expect(response).to redirect_to(orbits_url)
    end
  end
end
