# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/physics_bodies', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # PhysicsBody. As you add validations to PhysicsBody, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    attributes_for(:physics_body)
  end

  let(:invalid_attributes) do
    { foo: 'bar', fizz: 'bang' }
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      create(:physics_body)
      get physics_bodies_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      physics_body = create(:physics_body)
      get physics_body_url(physics_body)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_physics_body_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      physics_body = create(:physics_body)
      get edit_physics_body_url(physics_body)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    #   context 'with valid parameters' do
    #     it 'creates a new PhysicsBody' do
    #       expect do
    #         post physics_bodies_url, params: { physics_body: valid_attributes }
    #       end.to change(PhysicsBody, :count).by(1)
    #     end
    #
    #     it 'redirects to the created physics_body' do
    #       post physics_bodies_url, params: { physics_body: valid_attributes }
    #       expect(response).to redirect_to(physics_body_url(PhysicsBody.last))
    #     end
    #   end

    context 'with invalid parameters' do
      it 'does not create a new PhysicsBody' do
        expect do
          post physics_bodies_url, params: { physics_body: invalid_attributes }
        end.not_to change(PhysicsBody, :count)
      end

      it 'renders an unprocessable entity status' do
        post physics_bodies_url, params: { physics_body: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        attributes_for(:physics_body)
      end

      it 'updates the requested physics_body' do
        physics_body = create(:physics_body)
        patch physics_body_url(physics_body), params: { physics_body: new_attributes }
        physics_body.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the physics_body' do
        physics_body = create(:physics_body)
        patch physics_body_url(physics_body), params: { physics_body: new_attributes }
        physics_body.reload
        expect(response).to redirect_to(physics_body_url(physics_body))
      end
    end

    context 'with invalid parameters' do
      it 'renders a found status' do
        physics_body = create(:physics_body)
        patch physics_body_url(physics_body), params: { physics_body: invalid_attributes }
        expect(response).to have_http_status(:found)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested physics_body' do
      physics_body = create(:physics_body)
      expect do
        delete physics_body_url(physics_body)
      end.to change(PhysicsBody, :count).by(-1)
    end

    it 'redirects to the physics_bodies list' do
      physics_body = create(:physics_body)
      delete physics_body_url(physics_body)
      expect(response).to redirect_to(physics_bodies_url)
    end
  end
end
